const TEAMS = [
  { code: "ALG", name: "Algeria", flag: "🇩🇿" },
  { code: "ARG", name: "Argentina", flag: "🇦🇷" },
  { code: "AUS", name: "Australia", flag: "🇦🇺" },
  { code: "AUT", name: "Austria", flag: "🇦🇹" },
  { code: "BEL", name: "Belgium", flag: "🇧🇪" },
  { code: "BIH", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "BRA", name: "Brazil", flag: "🇧🇷" },
  { code: "CAN", name: "Canada", flag: "🇨🇦" },
  { code: "CPV", name: "Cape Verde", flag: "🇨🇻" },
  { code: "COL", name: "Colombia", flag: "🇨🇴" },
  { code: "COD", name: "DR Congo", flag: "🇨🇩" },
  { code: "CUW", name: "Curaçao", flag: "🇨🇼" },
  { code: "CZE", name: "Czechia", flag: "🇨🇿" },
  { code: "ECU", name: "Ecuador", flag: "🇪🇨" },
  { code: "EGY", name: "Egypt", flag: "🇪🇬" },
  { code: "ENG", name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { code: "FRA", name: "France", flag: "🇫🇷" },
  { code: "GER", name: "Germany", flag: "🇩🇪" },
  { code: "GHA", name: "Ghana", flag: "🇬🇭" },
  { code: "HTI", name: "Haiti", flag: "🇭🇹" },
  { code: "IRN", name: "Iran", flag: "🇮🇷" },
  { code: "IRQ", name: "Iraq", flag: "🇮🇶" },
  { code: "JOR", name: "Jordan", flag: "🇯🇴" },
  { code: "JPN", name: "Japan", flag: "🇯🇵" },
  { code: "CIV", name: "Ivory Coast", flag: "🇨🇮" },
  { code: "MAR", name: "Morocco", flag: "🇲🇦" },
  { code: "MEX", name: "Mexico", flag: "🇲🇽" },
  { code: "NED", name: "Netherlands", flag: "🇳🇱" },
  { code: "NZL", name: "New Zealand", flag: "🇳🇿" },
  { code: "NOR", name: "Norway", flag: "🇳🇴" },
  { code: "PAN", name: "Panama", flag: "🇵🇦" },
  { code: "PAR", name: "Paraguay", flag: "🇵🇾" },
  { code: "POR", name: "Portugal", flag: "🇵🇹" },
  { code: "QAT", name: "Qatar", flag: "🇶🇦" },
  { code: "KOR", name: "South Korea", flag: "🇰🇷" },
  { code: "RSA", name: "South Africa", flag: "🇿🇦" },
  { code: "KSA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "SCO", name: "Scotland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { code: "SEN", name: "Senegal", flag: "🇸🇳" },
  { code: "ESP", name: "Spain", flag: "🇪🇸" },
  { code: "SWE", name: "Sweden", flag: "🇸🇪" },
  { code: "SUI", name: "Switzerland", flag: "🇨🇭" },
  { code: "TUN", name: "Tunisia", flag: "🇹🇳" },
  { code: "TUR", name: "Turkey", flag: "🇹🇷" },
  { code: "USA", name: "United States", flag: "🇺🇸" },
  { code: "URU", name: "Uruguay", flag: "🇺🇾" },
  { code: "UZB", name: "Uzbekistan", flag: "🇺🇿" },
];

// Export the teams
module.exports = TEAMS;
