const TEAMS = [
  { code: "ALG", name: "Algeria" },
  { code: "ARG", name: "Argentina" },
  { code: "AUS", name: "Australia" },
  { code: "AUT", name: "Austria" },
  { code: "BEL", name: "Belgium" },
  { code: "BIH", name: "Bosnia and Herzegovina" },
  { code: "BRA", name: "Brazil" },
  { code: "CAN", name: "Canada" },
  { code: "CPV", name: "Cape Verde" },
  { code: "COL", name: "Colombia" },
  { code: "COD", name: "DR Congo" },
  { code: "CUW", name: "Curaçao" },
  { code: "CZE", name: "Czechia" },
  { code: "ECU", name: "Ecuador" },
  { code: "EGY", name: "Egypt" },
  { code: "ENG", name: "England" },
  { code: "FRA", name: "France" },
  { code: "GER", name: "Germany" },
  { code: "GHA", name: "Ghana" },
  { code: "HTI", name: "Haiti" },
  { code: "IRN", name: "Iran" },
  { code: "IRQ", name: "Iraq" },
  { code: "JOR", name: "Jordan" },
  { code: "JPN", name: "Japan" },
  { code: "CIV", name: "Ivory Coast" },
  { code: "MAR", name: "Morocco" },
  { code: "MEX", name: "Mexico" },
  { code: "NED", name: "Netherlands" },
  { code: "NZL", name: "New Zealand" },
  { code: "NOR", name: "Norway" },
  { code: "PAN", name: "Panama" },
  { code: "PAR", name: "Paraguay" },
  { code: "POR", name: "Portugal" },
  { code: "QAT", name: "Qatar" },
  { code: "KOR", name: "South Korea" },
  { code: "RSA", name: "South Africa" },
  { code: "KSA", name: "Saudi Arabia" },
  { code: "SCO", name: "Scotland" },
  { code: "SEN", name: "Senegal" },
  { code: "ESP", name: "Spain" },
  { code: "SWE", name: "Sweden" },
  { code: "SUI", name: "Switzerland" },
  { code: "TUN", name: "Tunisia" },
  { code: "TUR", name: "Turkey" },
  { code: "USA", name: "United States" },
  { code: "URU", name: "Uruguay" },
  { code: "UZB", name: "Uzbekistan" },
];

// Export the teams
module.exports = TEAMS;
